# Generated by Django 5.1.6 on 2025-02-25

from django.db import migrations
from django.utils import timezone
import os
from datetime import datetime, timezone as py_timezone

def create_initial_events(apps, schema_editor):
    Event = apps.get_model('core', 'Event')
    
    # Define base path for static images
    base_path = 'event_images/'
    
    # Create events
    events = [
        {
            'title': "School's Football Champion",
            'description': "Annual school football championship tournament. Come and support our young athletes!",
            'date': datetime(2025, 3, 30, 14, 0, tzinfo=py_timezone.utc),
            'location': "ABC Sport Salon",
            'status': 'upcoming',
            'max_participants': 50,
            'image': os.path.join(base_path, 'football.jpg')
        },
        {
            'title': "Choir Performance",
            'description': "Annual school choir showcase featuring talented student performers.",
            'date': datetime(2025, 4, 24, 18, 0, tzinfo=py_timezone.utc),
            'location': "ABC Amphitheater",
            'status': 'upcoming',
            'max_participants': 200,
            'image': os.path.join(base_path, 'choir.jpg')
        },
        {
            'title': "Summer Festival",
            'description': "School's annual summer festival. Free entrance and fun for everyone!",
            'date': datetime(2025, 7, 19, 11, 30, tzinfo=py_timezone.utc),
            'location': "Seehof Park",
            'status': 'upcoming',
            'max_participants': None,
            'image': os.path.join(base_path, 'summerfest.jpg')
        }
    ]
    
    # Create the events
    for event_data in events:
        Event.objects.create(**event_data)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_event_eventregistration'),
    ]

    operations = [
        migrations.RunPython(create_initial_events),
    ]
    